### PR TITLE
ZIO support

### LINKED ISSUE #459: ZIO support
Adding a module with native ZIO 2 integration would be cool, are you interested in any contributions?

### PR DESCRIPTION
**Pull request by Fristi**
Copy paste of CE2 and adjusted to ZIO. Resolves #459 

If all is good, would you be able to cut a release?

### CODE REVIEW

**Comment by majk-p** [comment]
Thanks for the PR, if you don't mind I'll revisit it once we are done with the transfer in https://github.com/ocadotechnology/sttp-oauth2/issues/477

**Comment by Fristi** [comment]
Building is failing https://github.com/polyvariant/sttp-oauth2/actions/runs/9079234922/job/24948085787#step:5:28 Should I revert back to old sbt version orsomething?

**Comment by majk-p** [comment]
Not sure yet, I'd guess you need to run `githubWorkflowGenerate` and commit again. I can have a look at it later this week.

**Comment by Fristi** [comment]
Did run it! Awaiting the build if it worked or not, think you not approve running the work right?

**Comment by Fristi** [comment]
https://github.com/polyvariant/sttp-oauth2/pull/460/commits/c2cc24fb2299da9cfeae37e3ceee9d4695417679 did't work

I now reverted back the sbt version

**Comment by Fristi** [comment]
When I revert back to the old version of sbt and run it locally it gives me

```
[info] loading global plugins from /Users/mark/.sbt/1.0/plugins
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.2.0, 1.0.6}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.7.3                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.7.3                      (depends on 1.3.0)
[error] 	    +- org.scala-sbt:librarymanagement-core_2.12:1.7.1    (depends on 1.2.0)
[error] 	    +- io.get-coursier:lm-coursier-shaded_2.12:2.0.12     (depends on 1.3.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over {1.3.0, 1.2.0, 1.0.6}
[error] 	    +- org.scala-lang:scala-compiler:2.12.17              (depends on 2.1.0)
[error] 	    +- org.scala-sbt:testing_2.12:1.7.3                   (depends on 1.3.0)
[error] 	    +- org.scala-sbt:sbinary_2.12:0.5.1                   (depends on 1.0.6)
[error] 	    +- org.scala-sbt:main_2.12:1.7.3                      (depends on 1.3.0)
[error] 	    +- org.scala-sbt:librarymanagement-core_2.12:1.7.1    (depends on 1.2.0)
[error] 	    +- io.get-coursier:lm-coursier-shaded_2.12:2.0.12     (depends on 1.3.0)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

**Comment by majk-p** [comment]
I just had a look and fixed the build. Unfortunately I didn't have push rights to your fork, so I just raised a new PR in https://github.com/polyvariant/sttp-oauth2/pull/487. Let's close this one and continue there

**Pull request closed without merging**
